### ISSUE TITLE
Arbeitgeber

### ISSUE THREAD

**Issue by revolvermann76** [IOIO72/ama#2]
Bei welchem Arbeitgeber bist Du gerade beschäftigt und was tust Du dort konkret?

**Comment by IOIO72** [comment]
Seit 1.12.2022 arbeite ich bei der [DB Systel](https://www.dbsystel.de/) als [UX Engineer](https://www.coursera.org/articles/what-is-a-ux-engineer) für das Team von [BahnID](https://id.bahn.de/), dem Single-Sign-On-Service der [Deutschen Bahn](https://www.deutschebahn.com/). Ich bin auf [React](https://reactjs.org/) und [Design Thinking](https://www.ibm.com/design/thinking/) spezialisiert.
