### ISSUE TITLE
Verschlüsselung

### ISSUE THREAD

**Issue by revolvermann76** [IOIO72/ama#3]
Frage: Bekomme ich jetzt ein Bienchen?

Wo Rechtschaffenheit im Herzen ist, ist Schönheit im Charakter. Wenn es Schönheit im Charakter gibt, gibt es Harmonie im Haus. Wenn zu Hause Harmonie herrscht, herrscht Ordnung in der Nation. Wenn es Ordnung in der Nation gibt, gibt es Frieden in der Welt.

**Comment by IOIO72** [comment]
Absolut! 🐝
